#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# Get multi-instances specific variables
app=$YNH_APP_INSTANCE_NAME

source /usr/share/yunohost/helpers # Source app helpers

# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)
final_path=$(ynh_app_setting_get "$app" final_path)

# Copy the app files
ynh_backup "$final_path" "sources" 1

# Copy the nginx conf files
ynh_backup "/etc/nginx/conf.d/${domain}.d/${app}.conf" "nginx.conf"
# Copy the php-fpm conf files
ynh_backup "/etc/php5/fpm/pool.d/${app}.conf" "php-fpm.conf"
ynh_backup "/etc/php5/fpm/conf.d/20-${app}.ini" "php-fpm.ini"