#!/bin/bash

# The parameter $1 is the backup directory location dedicated to the app
backup_dir=$1

# The parameter $2 is the id of the app instance ex: ynhexample__2
app=$2

path=$(sudo yunohost app setting $app directory)

cd $path
sudo bin/grav backup
sudo mkdir -p ${backup_dir}/var/www/grav
backup_file="$(ls -rt backup/ | tail -n 1)"
sudo cp backup/$backup_file ${backup_dir}/var/www/grav/
