#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

source .fonctions	# Loads the generic functions usually used in the script
source /usr/share/yunohost/helpers # Source app helpers

CLEAN_SETUP () {
	# Clean installation residues that are not supported by the remove script.
	# Clean hosts
	sudo sed -i '/#GRAV/d' /etc/hosts
}
TRAP_ON	# Active trap to stop the script if an error is detected.

domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
language=$YNH_APP_ARG_LANGUAGE
multisite=$YNH_APP_ARG_MULTISITE
is_public=$YNH_APP_ARG_IS_PUBLIC
install_admin=$YNH_APP_ARG_INSTALL_ADMIN
private_admin=$YNH_APP_ARG_PRIVATE_ADMIN
create_admin=$YNH_APP_ARG_CREATE_ADMIN

app=$YNH_APP_INSTANCE_NAME

CHECK_VAR "$app" "app name not set"

CHECK_PATH

CHECK_DOMAINPATH

CHECK_FINALPATH

ynh_app_setting_set $app domain $domain
ynh_app_setting_set $app path $path
ynh_app_setting_set $app is_public $is_public
ynh_app_setting_set $app language $language
ynh_app_setting_set $app multisite $multisite

# Creates the destination directory and stores its location.
sudo mkdir "$final_path"
ynh_app_setting_set $app final_path $final_path

# Install grav-plugin-admin
if [ "$install_admin" = "Yes" ]; then
    SETUP_SOURCE "core-admin" "grav-admin-v1.1.17.zip"
else
    SETUP_SOURCE "core" "grav-v1.1.17.zip"
fi

# Grav install
sudo $final_path/bin/grav

# Set permissions
sudo chown -R www-data: $final_path

echo -e "127.0.0.1 $domain #GRAV" | sudo tee -a /etc/hosts

# Copy nginx config
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Modif the variables in the nginx configuration file
sudo sed -i "s@__PATHTOCHANGE__@$path@g" /etc/nginx/conf.d/$domain.d/$app.conf
sudo sed -i "s@__FINALPATH__@$final_path@g" /etc/nginx/conf.d/$domain.d/$app.conf
sudo sed -i "s@__NAMETOCHANGE__@$app@g" /etc/nginx/conf.d/$domain.d/$app.conf

if [ "$multisite" = "Yes" ];
then
	sudo sed -i "s@#--MULTISITE--@@g" /etc/nginx/conf.d/$domain.d/$app.conf
fi

if [ "$is_public" = "Yes" ];
then
	sudo sed -i "s@#--PRIVATE--@@g" /etc/nginx/conf.d/$domain.d/$app.conf
fi

POOL_FPM

# Setup SSOwat
ynh_app_setting_set "$app" is_public "$is_public"
if [ "$is_public" = "Yes" ];
then
  ynh_app_setting_set "$app" unprotected_uris "/"
fi
# Make admin protected (if site is not)
if [ "$private_admin" = "Yes" ] && [ "$is_public" = "Yes" ]; then
    ynh_app_setting_set "$app" protected_uris "/admin"
fi

# Use SSOwat for admin interface
# add grav-plugin-httpbasicauth to use HTTP basic auth
# add grav-plugin-ynh to create first admin user
if [ "$install_admin" = "Yes" ] && [ "$private_admin" = "Yes" ] && [ "$create_admin" = "Yes" ]; then
    (cd $final_path && sudo bin/gpm install -n httpbasicauth)
    echo "Cloning grav-plugin-ynh..."
    sudo git clone https://github.com/lithrel/grav-plugin-ynh.git $final_path/user/plugins/ynh -b master
    sudo chown -R www-data: $final_path/user/plugins/httpbasicauth
    sudo chown -R www-data: $final_path/user/plugins/ynh
fi

# Set permissions (one last time)
sudo chown -R www-data: $final_path

# Reload SSOwat configuration
sudo yunohost app ssowatconf

# Reload Nginx and regenerate SSOwat conf
sudo service php5-fpm restart
sudo service nginx reload

# Nettoyer hosts
sudo sed -i '/#GRAV/d' /etc/hosts