#!/bin/bash
set -e
app=grav
SCRIPTPATH=$( cd $(dirname $0) ; pwd -P )

# Retrieve arguments
domain=$1
path=$2
is_public=$3
install_admin=$4
use_ssowat=$5

# Removal of trailing /
if [ "$path" = "/" ]; then
    echo "Installation on the root of the domain"
else
    path=${path%/}
fi

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app \
    || (echo "Path not available: $domain$path" && exit 1)

# Save app settings
#sudo yunohost app setting $app admin -v "$admin"

# Create source directory
final_path=/var/www/$app
sudo mkdir -p $final_path
sudo chown -R www-data: $final_path
sudo yunohost app setting $app domain -v "$domain"
sudo yunohost app setting $app path -v "$path"
sudo yunohost app setting $app directory -v "$final_path"

# Modify Nginx configuration file and copy it to Nginx conf directory
sudo sed -i "s@PATHTOCHANGE@$path@g" $SCRIPTPATH/../conf/nginx.conf
sudo sed -i "s@ALIASTOCHANGE@$final_path/@g" $SCRIPTPATH/../conf/nginx.conf
sudo sed -i "s@ROOTTOCHANGE@$final_path@g" $SCRIPTPATH/../conf/nginx.conf
sudo cp $SCRIPTPATH/../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Clone Grav Core & install Grav
sudo git clone https://github.com/getgrav/grav.git $final_path -b master
(cd $final_path && sudo php $final_path/bin/composer.phar install --no-dev -o)
sudo chown -R www-data: $final_path
(cd $final_path && sudo bin/grav install)

# Set permissions (again)
sudo chown -R www-data: $final_path

# Install grav-plugin-admin
if [ "$install_admin" = "Yes" ]; then
    (cd $final_path && sudo bin/gpm selfupgrade -f)
    (cd $final_path && sudo bin/gpm install -n admin)
    sudo chown -R www-data: $final_path
fi

# Make app public if necessary
sudo yunohost app setting $app is_public -v "$is_public"
if [ "$is_public" = "Yes" ]; then
    sudo yunohost app setting $app unprotected_uris -v "/"
fi

# Use SSOwat for admin interface
# add plugin to use HTTP basic auth
# add plugin to create admin user
if [ "$install_admin" = "Yes" ] && [ "$use_ssowat" = "Yes" ]; then
    sudo yunohost app setting $app protected_uris -v "/admin"
    (cd $final_path && sudo bin/gpm install -n httpbasicauth)
    sudo git clone https://github.com/lithrel/grav-plugin-ynh.git $final_path/user/plugins/ynh -b master
    sudo chown -R www-data: $final_path/user/plugins/httpbasicauth
    sudo chown -R www-data: $final_path/user/plugins/ynh
fi

# Set permissions (one last time)
sudo chown -R www-data: $final_path

sudo service nginx reload
sudo yunohost app ssowatconf