#!/bin/bash
set -e
app=grav
domain=$(sudo yunohost app setting $app domain)

sudo rm -rf /var/www/$app
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf

sudo service php5-fpm restart
sudo service nginx reload
sudo yunohost app ssowatconf