#!/bin/bash
set -eu

# The parameter $1 is the backup directory location dedicated to the app
backup_dir=$YNH_APP_BACKUP_DIR

# The parameter $2 is the id of the app instance ex: ynhexample__2
app=$YNH_APP_INSTANCE_NAME

path=$(sudo ynh_app_setting_get "$app" directory)
backup_file="$(ls -rt ${backup_dir}/var/www/grav/ | tail -n 1)"

if [ $backup_file = "" ]; then
    ynh_die "No backup found."
fi

sudo mkdir -p $path
sudo unzip $backup_file -d $path
