#!/bin/bash
set -eu

app=$YNH_APP_INSTANCE_NAME
domain=$(sudo ynh_app_setting_get "$app" domain)
path=$(sudo ynh_app_setting_get "$app" path)
directory=$(sudo ynh_app_setting_get "$app" directory)

(cd $directory && sudo bin/gpm selfupgrade)